
[profile.default]
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
remappings = [
  "forge-std=lib/forge-std/src/",
  "foundry-huff=lib/foundry-huff/src/",
]
[profile.default.fuzz]
runs = 20_000